### ISSUE TITLE
Hardcoded key in config.yml needs to be removed

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/metadefender-menlo-integration#127]
there's a hardcoded key here, https://github.com/k8-proxy/metadefender-menlo-integration/blob/develop/config.yml 

```
service: glasswall-cloud-sdk
api:
  params:
    apikey: dp2Ug1jtEh4xxFHpJBfWn9V7fKB3yVcv60lhwOAG
    gw_cloud_url: http://34.247.28.247:8080/api
server: 
  port: 3000
  host: "0.0.0.0"
  api_version: /api/v1
https:
  load_local: false
  crt: /tmp/certs/server.crt
  key: /tmp/certs/server.key
logging:
  enabled: true
  level: INFO
  logfile: /var/log/glasswall-menlo/app.log
  interval: 24
  backup_count: 30
```
